name: Collect US treasuries foreign holdings

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 20 * *'

jobs:
  run_script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install chrome
        uses: browser-actions/setup-chrome@v1

      - name: Test chrome
        run: chrome --version

      - name: Install chromedriver
        uses: nanasess/setup-chromedriver@v1

      - name: Test chromedriver
        run: timeout 5 chromedriver --url-base=/wd/hub || ( [[ $? -eq 124 ]] && echo "Chromedriver launched successfully" )

      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run parser script
        run: python src/foreign_treasury_holdings.py ${{ secrets.TG_API_TOKEN }}