name: Collect treasury holdings

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 20 * *'

jobs:
  run_script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install chrome
        uses: browser-actions/setup-chrome@v1
        run: chrome --version

      - name: Install chromedriver
        uses: nanasess/setup-chromedriver@v1
        run: chromedriver --url-base=/wd/hub  # export DISPLAY=:99 && chromedriver --url-base=/wd/hub & sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 &  # optional

      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run parser script
        run: python src/foreign_treasury_holdings.py ${{ secrets.TG_API_TOKEN }}