name: Collect inflation in Russia data from Rosstat

on:
  schedule:
    - cron: '5 16 * * 3'

jobs:
  run_script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run parser script
        run: python src/inflation_ru_rosstat.py ${{ secrets.TG_API_TOKEN }}
